name: core
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^4.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.3.0
  flutter_rating_bar: ^4.0.0
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  http: ^0.13.3
  path_provider: ^2.0.2
  provider: ^6.0.0
  sqflite_sqlcipher: ^2.1.0
  test_cov_console: ^0.1.5
  encrypt: ^5.0.1
  movie:
    path: ../movie
  tv_show:
    path: ../tv_show
  search:
    path: ../search
  about:
    path: ../about

dev_dependencies:
  build_runner: ^2.0.4
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
