// Mocks generated by Mockito 5.0.16 from annotations
// in tv_show/test/presentation/pages/tv_show_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:core/common/state_enum.dart' as _i9;
import 'package:core/domain/entities/tv_show.dart' as _i10;
import 'package:core/domain/entities/tv_show_detail.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_show/domain/usecases/get_tv_show_detail.dart' as _i2;
import 'package:tv_show/domain/usecases/get_tv_show_recommendations.dart'
    as _i3;
import 'package:tv_show/presentation/provider/tv_show_detail_notifier.dart'
    as _i8;
import 'package:watchlist/domain/usecases/get_watchlist_status_tv_show.dart'
    as _i4;
import 'package:watchlist/domain/usecases/remove_watchlist_tv_show.dart' as _i6;
import 'package:watchlist/domain/usecases/save_watchlist_tv_show.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTvShowDetail_0 extends _i1.Fake implements _i2.GetTvShowDetail {}

class _FakeGetTvShowRecommendations_1 extends _i1.Fake
    implements _i3.GetTvShowRecommendations {}

class _FakeGetWatchListStatusTvShow_2 extends _i1.Fake
    implements _i4.GetWatchListStatusTvShow {}

class _FakeSaveWatchlistTvShow_3 extends _i1.Fake
    implements _i5.SaveWatchlistTvShow {}

class _FakeRemoveWatchlistTvShow_4 extends _i1.Fake
    implements _i6.RemoveWatchlistTvShow {}

class _FakeTvShowDetail_5 extends _i1.Fake implements _i7.TvShowDetail {}

/// A class which mocks [TvShowDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowDetailNotifier extends _i1.Mock
    implements _i8.TvShowDetailNotifier {
  MockTvShowDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvShowDetail get getTvShowDetail =>
      (super.noSuchMethod(Invocation.getter(#getTvShowDetail),
          returnValue: _FakeGetTvShowDetail_0()) as _i2.GetTvShowDetail);
  @override
  _i3.GetTvShowRecommendations get getTvShowRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTvShowRecommendations),
              returnValue: _FakeGetTvShowRecommendations_1())
          as _i3.GetTvShowRecommendations);
  @override
  _i4.GetWatchListStatusTvShow get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeGetWatchListStatusTvShow_2())
          as _i4.GetWatchListStatusTvShow);
  @override
  _i5.SaveWatchlistTvShow get saveWatchlist => (super.noSuchMethod(
      Invocation.getter(#saveWatchlist),
      returnValue: _FakeSaveWatchlistTvShow_3()) as _i5.SaveWatchlistTvShow);
  @override
  _i6.RemoveWatchlistTvShow get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeRemoveWatchlistTvShow_4())
          as _i6.RemoveWatchlistTvShow);
  @override
  _i7.TvShowDetail get tvShow => (super.noSuchMethod(Invocation.getter(#tvShow),
      returnValue: _FakeTvShowDetail_5()) as _i7.TvShowDetail);
  @override
  _i9.RequestState get tvShowState =>
      (super.noSuchMethod(Invocation.getter(#tvShowState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  List<_i10.TvShow> get tvShowRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvShowRecommendations),
          returnValue: <_i10.TvShow>[]) as List<_i10.TvShow>);
  @override
  _i9.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTvShowDetail(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchTvShowDetail, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tvShow]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [tvShow]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
      Invocation.method(#loadWatchlistStatus, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
